server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          default-label: main
        # ?? native ?? (?? ??)
        # native:
        #   search-locations: classpath:/config

eureka:
  client:
    enabled: false  # ?? ??? ????
    register-with-eureka: false
    fetch-registry: false